const teams = [
    {
        "name": "Otters FC",
        "shortName": "OTT",
        "position": 0,
        "prevPosition": '',
        "id": 0,
        "color": 'saddlebrown',
        "badge": 'otter',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Wizards FC",
        "shortName": "WIZ",
        "position": 1,
        "prevPosition": '',
        "id": 1,
        "color": 'darkblue',
        "badge": 'hat-wizard',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Shrimp FC",
        "shortName": "SHR",
        "position": 2,
        "prevPosition": '',
        "id": 2,
        "color": 'orangered',
        "badge": 'shrimp',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Dragons FC",
        "shortName": "DRG",
        "position": 3,
        "prevPosition": '',
        "id": 3,
        "color": 'forestgreen',
        "badge": 'dragon',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Doggies FC",
        "shortName": "DOG",
        "position": 4,
        "prevPosition": '',
        "id": 4,
        "color": 'darkslategray',
        "badge": 'dog',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Kittycats FC",
        "shortName": "KIT",
        "position": 5,
        "prevPosition": '',
        "id": 5,
        "color": 'darkslateblue',
        "badge": 'shield-cat',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Stallions FC",
        "shortName": "STL",
        "position": 6,
        "prevPosition": '',
        "id": 6,
        "color": 'maroon',
        "badge": 'horse-head',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Frogs FC",
        "shortName": "FRG",
        "position": 7,
        "prevPosition": '',
        "id": 7,
        "color": 'lightseagreen',
        "badge": 'frog',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Rockets FC",
        "shortName": "ROC",
        "position": 8,
        "prevPosition": '',
        "id": 8,
        "color": 'mediumvioletred',
        "badge": 'rocket',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    },
    {
        "name": "Crows FC",
        "shortName": "CRW",
        "position": 9,
        "prevPosition": '',
        "id": 9,
        "color": 'black',
        "badge": 'crow',
        "won": 0,
        "lost": 0,
        "drawn": 0,
        "points": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "results": [],
        "opponents": [],
        "matchesPlayed": []
    }
];

export default teams;
